### ISSUE TITLE
A timeout is taking down the service.

### ISSUE THREAD

**Issue by nataren** [nataren/mtflow#25]
2015/04/15 03:01:14 The received command: @mtbot stop pr
2015/04/15 03:01:14 I will handle 'stop pr' command

2015/04/15 03:01:44 dial tcp 54.204.29.44:8082: i/o timeout
panic: dial tcp 54.204.29.44:8082: i/o timeout

goroutine 25 [running]:
log.Panic(0xc20830fef8, 0x1, 0x1)
        /usr/local/go/src/log/log.go:307 +0xb9
main.handleCommand(0x2, 0x1, 0xc208251040, 0x1, 0xa, 0xc2082b7e60)
        /Users/cesar/src/mtflow/handler.go:110 +0x1039
created by main.func·001
        /Users/cesar/src/mtflow/handler.go:49 +0x7f

goroutine 1 [chan receive]:
main.main()
        /Users/cesar/src/mtflow/mtflow.go:164 +0x146b

goroutine 16 [chan receive]:
main.RunCommandHandler(0xc2082b6d80, 0xc2082b6d20)
        /Users/cesar/src/mtflow/handler.go:41 +0x137
created by main.main
        /Users/cesar/src/mtflow/mtflow.go:160 +0x1433

goroutine 15 [select]:
net/http.(*persistConn).roundTrip(0xc20830a160, 0xc2082981a0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1082 +0x7ad
net/http.(*Transport).RoundTrip(0xc20805c090, 0xc20803fee0, 0xd, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:235 +0x558
net/http.send(0xc20803fee0, 0x7fa0614cfd40, 0xc20805c090, 0xc8, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:219 +0x4fc
net/http.(*Client).send(0xc20803cae0, 0xc20803fee0, 0xc8, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:142 +0x15b
net/http.(*Client).doFollowingRedirects(0xc20803cae0, 0xc20803fee0, 0x775248, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:367 +0xb25
net/http.(*Client).Do(0xc20803cae0, 0xc20803fee0, 0xc20803a229, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:177 +0x192
github.com/wm/go-flowdock/flowdock.(*Client).Do(0xc208034370, 0xc20803fee0, 0x67d940, 0xc20800ad80, 0x0, 0x0, 0x0)
        /Users/cesar/src/github.com/wm/go-flowdock/flowdock/flowdock.go:135 +0x5f
github.com/wm/go-flowdock/flowdock.(*MessagesService).Create(0xc208042030, 0xc2082510e0, 0x3f, 0x0, 0x0, 0x0)
        /Users/cesar/src/github.com/wm/go-flowdock/flowdock/messages.go:139 +0x1a0
main.func·002(0x753650, 0x3f)
        /Users/cesar/src/mtflow/mtflow.go:28 +0xfd
main.func·003()
        /Users/cesar/src/mtflow/mtflow.go:153 +0x85
created by main.main
        /Users/cesar/src/mtflow/mtflow.go:155 +0x131a

goroutine 14 [IO wait]:
net.(*pollDesc).Wait(0xc208011c60, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208011c60, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208011c00, 0xc2081b3800, 0x400, 0x400, 0x0, 0x7fa0614cfb70, 0xc2082a5f60)
        /usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208042120, 0xc2081b3800, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc208235ad0, 0x7fa0614d1330, 0xc208042120, 0x5, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc20808f340, 0x17, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0xc20808f340, 0xc20809f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:904 +0x166
net/http.noteEOFReader.Read(0x7fa0614d5cb0, 0xc20808f340, 0xc20806fd38, 0xc20809f000, 0x1000, 0x1000, 0x8, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc2082ad7e0, 0xc20809f000, 0x1000, 0x1000, 0x8, 0x0, 0x0)
        <autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc2082b7aa0)
        /usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc2082b7aa0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:295 +0x257
net/http/internal.readLine(0xc2082b7aa0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/internal/chunked.go:110 +0x5a
net/http/internal.(*chunkedReader).beginChunk(0xc2081d7650)
        /usr/local/go/src/net/http/internal/chunked.go:47 +0x46
net/http/internal.(*chunkedReader).Read(0xc2081d7650, 0xc2082f3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/internal/chunked.go:77 +0xbb
net/http.(*body).readLocked(0xc2081ad3c0, 0xc2082f3000, 0x1000, 0x1000, 0xffffffff, 0x0, 0x0)
        /usr/local/go/src/net/http/transfer.go:584 +0x7a
net/http.(*body).Read(0xc2081ad3c0, 0xc2082f3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transfer.go:579 +0x115
net/http.(*bodyEOFSignal).Read(0xc2081ad480, 0xc2082f3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1193 +0x285
bufio.(*Reader).fill(0xc2082b7bc0)
        /usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc2082b7bc0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadLine(0xc2082b7bc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:324 +0x62
github.com/bernerdschaefer/eventsource.(*Decoder).ReadField(0xc2082a4f60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/cesar/src/github.com/bernerdschaefer/eventsource/decoder.go:49 +0xd0
github.com/bernerdschaefer/eventsource.(*Decoder).Decode(0xc2082a4f60, 0xc20829a000, 0x0, 0x0)
        /Users/cesar/src/github.com/bernerdschaefer/eventsource/decoder.go:94 +0x73
github.com/bernerdschaefer/eventsource.(*EventSource).Read(0xc208237ae0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/cesar/src/github.com/bernerdschaefer/eventsource/eventsource.go:119 +0xb0
github.com/wm/go-flowdock/flowdock.func·001()
        /Users/cesar/src/github.com/wm/go-flowdock/flowdock/messages.go:50 +0x45
created by github.com/wm/go-flowdock/flowdock.(*MessagesService).Stream
        /Users/cesar/src/github.com/wm/go-flowdock/flowdock/messages.go:60 +0x402

goroutine 10 [sleep]:
net.func·019()
        /usr/local/go/src/net/dnsclient_unix.go:240 +0x5a
created by net.loadConfig
        /usr/local/go/src/net/dnsclient_unix.go:269 +0x20c

goroutine 22 [select]:
net/http.(*persistConn).readLoop(0xc20806fce0)
        /usr/local/go/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 23 [select]:
net/http.(*persistConn).writeLoop(0xc20806fce0)
        /usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:661 +0xcbc

goroutine 35 [IO wait]:
net.(*pollDesc).Wait(0xc20823f020, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20823f020, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20823efc0, 0xc20824e800, 0x400, 0x400, 0x0, 0x7fa0614cfb70, 0xc20827f180)
        /usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc2080421e8, 0xc20824e800, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc208184cc0, 0x7fa0614d1330, 0xc2080421e8, 0x5, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc20808f600, 0x17, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0xc20808f600, 0xc208324000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:904 +0x166
net/http.noteEOFReader.Read(0x7fa0614d5cb0, 0xc20808f600, 0xc20830a1b8, 0xc208324000, 0x1000, 0x1000, 0x7fa0614be010, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc208283200, 0xc208324000, 0x1000, 0x1000, 0xc207ffbdde, 0x0, 0x0)
        <autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc20833c060)
        /usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc20833c060, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc20830a160)
        /usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 36 [select]:
net/http.(*persistConn).writeLoop(0xc20830a160)
        /usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:661 +0xcbc

**Comment by nataren** [comment]
Fixed by  38b6d77
